x = input('Enter your name: ')
o = int(input("Your age:"))
e = float(input("Your money:"))
print("your name", x, 'old year', o, 'and cash money ',  e, )
print("id name", id(x), "id age", id(o), "id money", id(e))